chikitsa/urls.py
from django.contrib import admin
#from django.urls import path

from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('chikitsa/', include('homepage.urls'))
]

homepage/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf.urls import url
from django.urls import is_valid_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^medicines/$', views.all, name='medicines'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^bookappt/$', views.bookappt, name='bookappt'),
    url(r'^signup/$', views.register, name='signup'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

                  #url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name='add_to_cart'),
    #url(r'^order-summary/$', views.order_details, name='order_summary'),
    #url(r'^login/$', views.login_user, name='login'),
    url(r'^products/(?P<slug>[^\/]+)\/add$', views.add_to_cart, name='add_to_cart'),
    url(r'^products/(?P<id>\d+)\/remove$', views.remove_from_cart,name='remove_from_cart'),
    url(r'^products/(?P<slug>[^\/]+)\/?', views.detail, name='detail'),
    url(r'^products/$', views.all, name='all'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<search_id>.+)/', views.search, name='results'),

    url(r'^cart/$', views.view_cart, name='view_cart'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^orders/$', views.orders, name='orders'),

                  #url(r'^index/$', views.index, name='index'),

              ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homepage/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator


#User= get_user_model()
unicode = str
VARIATION_CATEGORIES = (
                ('size', 'Size'),
                ('color', 'Color'),
                ('package', 'Package'),
            )

class Medicines(models.Model):
    #user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    description=models.CharField(max_length=300)
    exp_date=models.DateField(default=datetime.now)
    availability=models.IntegerField()
    price=models.IntegerField()
    prescription=models.BooleanField(default=True)


    def __str__(self):
        return self.name + ' - ' + self.description

class Doctor(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Appt(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    age=models.IntegerField()
    time=models.TimeField(default=datetime.now)
    doctor=models.CharField(max_length=50)


    def __str__(self):
        return self.doctor


class Cart(models.Model):
        #user = models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
        user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
        created_at = models.DateTimeField(default=datetime.now)
        updated_at = models.DateTimeField(default=datetime.now)
        active = models.BooleanField(default=True)

        def __str__(self):
            return self.user.username

class Product(models.Model):
        title = models.CharField(max_length=120, null=False, blank=False)
        description = models.TextField(null=True, blank=True)
        price = models.DecimalField(decimal_places=2, max_digits=100, default=100.00,
                                            validators=[MinValueValidator(0)])
        slug = models.SlugField(unique=True)
        created_at = models.DateTimeField(default=datetime.now)
        updated_at = models.DateTimeField(default=datetime.now)
        active = models.BooleanField(default=True)

        def get_absolute_url(self):
            kwargs = {'slug': self.slug}
            return unicode(reverse('detail', kwargs=kwargs))

        def __unicode__(self):
            return self.title

class VariationManager(models.Manager):
        def all(self):
            return super(VariationManager, self).filter(active=True)

        def all_sizes(self):
            return self.all().filter(category='size')

        def all_colors(self):
            return self.all().filter(category='color')

        def variation_by_category(self):
            return [(category[0], self.filter(category=category[0])) for category in VARIATION_CATEGORIES]


class Variation(models.Model):
    """A variation on a particular product"""
    product = models.ForeignKey(Product, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    category = models.CharField(max_length=120, choices=VARIATION_CATEGORIES,
                                default=VARIATION_CATEGORIES[0])
    # image = models.ForeignKey(ProductImage, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100,
                                validators=[MinValueValidator(0)], null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    objects = VariationManager()

    def __unicode__(self):
        return ' | ' + self.title + ' | <' + self.category + '> of ' + self.product.title

class CartItem(models.Model):
        cart = models.ForeignKey(Cart, default=1, blank=True, on_delete=models.CASCADE)
        product = models.ForeignKey(Product, default=1, on_delete=models.CASCADE)
        variations = models.ManyToManyField(Variation, blank=True)
        quantity = models.IntegerField(default=0)
        created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
        updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)
        active = models.BooleanField(default=True)

        def __unicode__(self):
            return 'Order #' + unicode(self.id) + ' of ' + self.product.title

ORDER_STATUS = (
            ('started', 'Started'),
            ('abandoned', 'Abandoned'),
            ('finished', 'Finished'),
        )

class Order(models.Model):
            user = models.ForeignKey(User, default=1, null=True, on_delete=models.CASCADE)
            order_id = models.CharField(unique=True, max_length=120, default='abc')
            cart = models.ForeignKey(Cart, default=1,on_delete=models.CASCADE)
            status = models.CharField(max_length=255, choices=ORDER_STATUS, default='started')
            created_at = models.DateTimeField(auto_now_add=True)
            modified_at = models.DateTimeField(auto_now=True)

            subtotal = models.DecimalField(default=1000.0, max_digits=300, decimal_places=2)
            tax_amount = models.DecimalField(default=1000.0, max_digits=300, decimal_places=2)

            def total(self):
                return self.subtotal + self.tax_amount

            def __unicode__(self):
                return '<Order:' + self.order_id + '> ' + self.status + ' | ' + unicode(self.created_at)

            '''
            class Profile(models.Model):
                user=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
                objects=models.ManyToManyField(Medicines,blank=True)

                def __str__(self):
                    return self.user.username

            def post_save_profile_create(sender,instance,created, *args, **kwargs):
                if created:
                    Profile.objects.get_or_create(user=instance)

            post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

            class OrderItem(models.Model):
                product=models.OneToOneField(Medicines, on_delete=models.SET_NULL, null=True)
                is_ordered=models.BooleanField(default=False)
                date_added=models.DateTimeField(auto_now=True)
                date_ordered=models.DateTimeField(null=True)

                def __str__(self):
                    return self.product.name

            class Order(models.Model):
                ref_code=models.CharField(max_length=15)
                owner=models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
                is_ordered=models.BooleanField(default=False)
                items=models.ManyToManyField(OrderItem)
                date_ordered=models.DateTimeField(auto_now=True)

                def get_cart_items(self):
                    return self.items.all()
                def get_cart_total(self):
                    return sum([item.product.price for item in self.items.all()])

                def __str__(self):
                    return '{0}-{1}'.format(self.owner, self.ref_code)
            '''



# Create your models here.

homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Appt,Doctor
from django.utils import timezone


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class ApptForm(forms.ModelForm):
    age=forms.IntegerField()
    #time=forms.TimeField()
    doctor=forms.CharField(max_length=50)

    class Meta:
        model = Appt
        fields = ['user', 'age', 'time', 'doctor',]

homepage/templates/homepage/all.html
{% extends 'homepage/base_visitor.html' %}

{% load staticfiles %}

{% block body %}
    <h1>Medicine Store</h1>
    <div class="row">
        {% if request.GET.name %}
            <h1>{{ message }}</h1>
        {% else %}
        <form method="get" action="{% url 'search' %}"> <input name="name" value="{{ request.GET.name}}" ><button type="submit">Search</button></form>
        {% endif %}
        {% for product in all_products %}
            <div class="col-sm-6 col-md-4">

                <div class="thumbnail">
                    <img class="img-responsive" src="{% static 'homepage/images/img1.jpg' %}"
                         alt="...">


                    <div class="caption">
                        <h3>
                            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>

                        </h3>

                        <p>{{ product.price }}</p>

                        <p><a href="{% url 'detail' product.id %}" class="btn btn-primary" role="button">Order</a> </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Chikitsa{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'homepage/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'homepage' %}">Chikitsa</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'homepage' %}">Home</a></li>
                <li><a href="{% url 'medicines' %}">Order Medicines</a></li>

                <li><a href="{% url 'bookappt' %}">Book Appointment</a></li>
            </ul>
            <!--
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>-->
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'bookappt' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Book Appointment
                    </a>
                </li>
                <li>
                    <a href="{% url 'logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

homepage/templates/homepage/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Chikitsa{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'homepage/js/main.js' %}"></script>
</head>
<body id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url(images/img_bg_1.jpg);" data-stellar-background-ratio="0.5">
<!--<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url(images/img_bg_1.jpg);" data-stellar-background-ratio="0.5">
-->

<nav class="navbar navbar-inverse">
    <div class="container-fluid">




        <!-- Header -->
        <div class="navbar-header">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.5/waypoints.min.js"></script>
            <script src="/static/homepage/js/jquery.countTo.js" type="text/javascript"></script>
            <script src="/static/homepage/js/jquery.stellar.min.js"></script>
            <script src="/static/homepage/js/owl.carousel.min.js"></script>





            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'homepage' %}">Chikitsa</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'signup' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'login' %}">Log In</a></li>
                                <li><a href="{% url 'homepage' %}">Home</a></li>

							<li><a href="{% url 'medicines' %}">Order Medicines</a></li>
                            <li><a href="{% url 'view_cart' %}">View Cart</a></li>

							<li><a href="{% url 'bookappt' %}">Book Appointment</a></li>
                            <li><a href="{% url 'contact' %}">Contact</a></li>

                <li class="btn-cta"><a href="{% url 'logout_user' %}"><span>Logout</span></a></li>

            </ul>
        </div>

    </div>
</nav>

{% block body %}
{% endblock %}
</header>
</body>
</html>

homepage/templates/homepage/bookappt.html
{% extends 'homepage/base_visitor.html' %}
{% block title %}Book an Appointment{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Book an Appointment</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'homepage/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Chikitsa?</h3>
                    <p>Chikitsa is an app that allows you to book appointments of several doctors all at one place. It also allows you to purchase medicines online!</p>
                    <h3>How do I book an appointment?</h3>
                    <p>First, register on our site by going to the signup page. If you are already a registered user, then login to your account.Once you are logged in,book an appointment by filling in the necessary fields on this page </p>
                                    </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

homepage/templates/homepage/checkout.html
{% extends 'homepage/base_visitor.html' %}

{% block body %}


<h2 style="text-align: center; font-size: 40px; margin-top: 250px;">Your cart has been saved successfully!</h2>

{% endblock %}

homepage/templates/homepage/detail.html
{% extends 'homepage/base_visitor.html' %}


{% block body %}
    <div class="">
        <div class="row">
            <div class="page-header col-sm-10">
                <h1>{{ product.title }}</h1>
            </div>
            <div class="col-sm-2">
                <form action="{% url 'add_to_cart' product.slug %}" method="POST">
                    {% csrf_token %}

                    <button class="btn btn-success btn-block">
                        Add to Cart
                    </button>
                    <br/>

                    <div class="input-group">
                        <label for="qty">Quantity</label>
                        <input type="number" class="form-control" name="qty" value="1" min="1" max="100000"/>

                        {%  for variation_group in product.variation_set.variation_by_category %}
                            {% if variation_group.1 %}
                            <div class="control-group">
                                <label for="{{ variation_group.0 }}">{{ variation_group.0 | capfirst }}</label>
                                <select name="{{ variation_group.0 }}" class="form-control">
                                        {% for variation in variation_group.1 %}
                                            {{ variation }}
                                        <option value="{{ variation.id }}">{{ variation.title }}</option>
                                        {% endfor %}
                                </select>
                            </div>
                            {% endif %}
                        {% endfor  %}

                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">
            {% for image in product.productimage_set.all %}
                <img class="img-responsive" src="{{ MEDIA_URL }}{{ image.image }}"/>
            {% endfor %}
        </div>
        <div class="col-sm-10">
            <p>Price: ${{ product.price }}</p>
            <hr/>
            {{ product.description }}
        </div>
    </div>
{% endblock %}

homepage/templates/homepage/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

homepage/templates/homepage/login.html
{% extends 'homepage/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'login' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'signup' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

homepage/templates/homepage/meds.html
{% load staticfiles %}
<h1>Welcome to the Medicines Page</h1>
<h1>{{ meds.name }}</h1>
<h3>{{ meds.description }}</h3>

<ul>
    {% for meds in meds.medicines_set.all  %}
    <li>{{meds.name}}-{{ meds.price }} </li>
    {%  endfor %}
</ul>

homepage/templates/homepage/orders.html
{% extends 'homepage/base_visitor.html' %}

{% block body %}
    <h1>My Orders</h1>
    <ul>
        {% for order in user.order_set.all %}
        <li>{{ order }}</li>
        {% endfor %}
    </ul>
{% endblock %}

homepage/templates/homepage/search.html
{% extends 'homepage/base_visitor.html' %}

{% load staticfiles %}


{% block body %}

{% if request.GET.name %}
            <h1>{{ message }}</h1>
        {% else %}
        <form method="get" action="{% url 'search' %}"> <input name="name" value="{{ request.GET.name}}" ><button type="submit">Search</button></form>
        {% endif %}

<h2 style="color:blue">Searched for: "{{ search_query }}"</h2>
<h2 >Results:</h2>
    <ul>
    {% for product in results %}
            <li>
                <div class="col-sm-6 col-md-4">

                <div class="thumbnail">
                    <img class="img-responsive" src="{% static 'homepage/images/img1.jpg' %}"
                         alt="...">


                    <div class="caption">
                        <h3>
                            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>

                        </h3>

                        <p>Price: Rs {{ product.price }}</p>


                    </div>
                </div>
            </div>
            </li>
    {% endfor %}
    </ul>
    </header>

{% endblock %}

homepage/templates/homepage/signup.html
{% extends 'homepage/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url(images/img_bg_1.jpg);" data-stellar-background-ratio="0.5">

<div class="container-fluid" >

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'homepage/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'login' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>
</header>
{% endblock %}

homepage/templates/homepage/view_cart.html
{% extends 'homepage/base_visitor.html' %}

{% load staticfiles %}



{% block body %}
    <div class="page-header">
        <h1>Your Shopping Cart</h1>
    </div>
    <div class="row">
        <table class="table">
            <thead>
            <th>Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th></th>
            </thead>
            <tbody>
            {% for item in cart_items %}
                <tr>
                    <td>
                        {{ item.product.title }}
                        <ul>
                            {%  for  variation in item.variations.all %}
                            <li>{{ variation.title }}</li>
                        {% endfor %}
                        </ul>
                    </td>

                    <td>{{ item.quantity }}</td>
                    <td>Rs.{{ item.product.price }}</td>
                    <td>
                        <form action="{% url 'remove_from_cart' item.id %}" method="POST">
                            {% csrf_token %}
                            <button>Remove</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td>Total</td>
                <td></td>
                <td>Rs.{{ order_total }}</td>
                <td></td>
            </tr>
            </tfoot>
        </table>
        <a class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
    </div>
{% endblock %}